title: Teresa Nguyen
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

collections:
  blog:
    output: true
    permalink: /blog/:title/

header_pages:
  - index.md
  - projects.md
  - blog.md
  - resume.md
